# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_wfsclient.ui'
#
# Created by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_WfsClient(object):
    def setupUi(self, WfsClient):
        WfsClient.setObjectName(_fromUtf8("WfsClient"))
        WfsClient.resize(520, 648)
        WfsClient.setWindowTitle(QtGui.QApplication.translate("WfsClient", "WFS 2.0 Client - Version 0.9.0 beta", None, QtGui.QApplication.UnicodeUTF8))
        self.lblOnlineResource = QtGui.QLabel(WfsClient)
        self.lblOnlineResource.setGeometry(QtCore.QRect(20, 10, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lblOnlineResource.setFont(font)
        self.lblOnlineResource.setText(QtGui.QApplication.translate("WfsClient", "WFS 2.0 OnlineResource", None, QtGui.QApplication.UnicodeUTF8))
        self.lblOnlineResource.setObjectName(_fromUtf8("lblOnlineResource"))
        self.txtUrl = QtGui.QLineEdit(WfsClient)
        self.txtUrl.setGeometry(QtCore.QRect(20, 30, 481, 20))
        self.txtUrl.setText(QtGui.QApplication.translate("WfsClient", "http://geoserv.weichand.de:8080/geoserver/wfs", None, QtGui.QApplication.UnicodeUTF8))
        self.txtUrl.setObjectName(_fromUtf8("txtUrl"))
        self.chkAuthentication = QtGui.QCheckBox(WfsClient)
        self.chkAuthentication.setGeometry(QtCore.QRect(20, 60, 261, 17))
        self.chkAuthentication.setText(QtGui.QApplication.translate("WfsClient", "Authentication required", None, QtGui.QApplication.UnicodeUTF8))
        self.chkAuthentication.setObjectName(_fromUtf8("chkAuthentication"))
        self.frmMain = QtGui.QFrame(WfsClient)
        self.frmMain.setGeometry(QtCore.QRect(10, 90, 501, 551))
        self.frmMain.setAutoFillBackground(False)
        self.frmMain.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frmMain.setFrameShadow(QtGui.QFrame.Raised)
        self.frmMain.setObjectName(_fromUtf8("frmMain"))
        self.progressBar = QtGui.QProgressBar(self.frmMain)
        self.progressBar.setGeometry(QtCore.QRect(130, 480, 361, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.cmdListStoredQueries = QtGui.QPushButton(self.frmMain)
        self.cmdListStoredQueries.setEnabled(True)
        self.cmdListStoredQueries.setGeometry(QtCore.QRect(150, 10, 131, 23))
        self.cmdListStoredQueries.setText(QtGui.QApplication.translate("WfsClient", "List StoredQueries", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdListStoredQueries.setObjectName(_fromUtf8("cmdListStoredQueries"))
        self.txtFeatureTypeDescription = QtGui.QPlainTextEdit(self.frmMain)
        self.txtFeatureTypeDescription.setGeometry(QtCore.QRect(10, 140, 481, 51))
        self.txtFeatureTypeDescription.setReadOnly(True)
        self.txtFeatureTypeDescription.setObjectName(_fromUtf8("txtFeatureTypeDescription"))
        
        self.lblMessage = QtGui.QLabel(self.frmMain)
        self.lblMessage.setGeometry(QtCore.QRect(10, 520, 481, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lblMessage.setFont(font)
        self.lblMessage.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblMessage.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblMessage.setText(_fromUtf8(""))
        self.lblMessage.setObjectName(_fromUtf8("lblMessage"))
        self.cmbFeatureType = QtGui.QComboBox(self.frmMain)
        self.cmbFeatureType.setGeometry(QtCore.QRect(10, 70, 341, 22))
        self.cmbFeatureType.setObjectName(_fromUtf8("cmbFeatureType"))
        self.cmdGetCapabilities = QtGui.QPushButton(self.frmMain)
        self.cmdGetCapabilities.setGeometry(QtCore.QRect(10, 10, 131, 23))
        self.cmdGetCapabilities.setText(QtGui.QApplication.translate("WfsClient", "GetCapabilities", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdGetCapabilities.setObjectName(_fromUtf8("cmdGetCapabilities"))
        self.txtCount = QtGui.QLineEdit(self.frmMain)
        self.txtCount.setGeometry(QtCore.QRect(100, 410, 131, 20))
        self.txtCount.setText(QtGui.QApplication.translate("WfsClient", "50", None, QtGui.QApplication.UnicodeUTF8))
        self.txtCount.setObjectName(_fromUtf8("txtCount"))
        self.lblInfo = QtGui.QLabel(self.frmMain)
        self.lblInfo.setGeometry(QtCore.QRect(10, 50, 481, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lblInfo.setFont(font)
        self.lblInfo.setText(QtGui.QApplication.translate("WfsClient", "FeatureTypes", None, QtGui.QApplication.UnicodeUTF8))
        self.lblInfo.setObjectName(_fromUtf8("lblInfo"))
        self.lblCount = QtGui.QLabel(self.frmMain)
        self.lblCount.setGeometry(QtCore.QRect(10, 410, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lblCount.setFont(font)
        self.lblCount.setText(QtGui.QApplication.translate("WfsClient", "FeatureLimit", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCount.setObjectName(_fromUtf8("lblCount"))
        self.cmdGetFeature = QtGui.QPushButton(self.frmMain)
        self.cmdGetFeature.setEnabled(False)
        self.cmdGetFeature.setGeometry(QtCore.QRect(10, 480, 111, 23))
        self.cmdGetFeature.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.cmdGetFeature.setText(QtGui.QApplication.translate("WfsClient", "GetFeature(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdGetFeature.setObjectName(_fromUtf8("cmdGetFeature"))
        self.frmParameter = QtGui.QFrame(self.frmMain)
        self.frmParameter.setEnabled(True)
        self.frmParameter.setGeometry(QtCore.QRect(0, 200, 501, 271))
        self.frmParameter.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frmParameter.setFrameShadow(QtGui.QFrame.Raised)
        self.frmParameter.setObjectName(_fromUtf8("frmParameter"))
        self.gridLayoutWidget = QtGui.QWidget(self.frmParameter)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 481, 231))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.frmExtent = QtGui.QFrame(self.frmMain)
        self.frmExtent.setEnabled(True)
        self.frmExtent.setGeometry(QtCore.QRect(0, 200, 501, 191))
        self.frmExtent.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frmExtent.setFrameShadow(QtGui.QFrame.Raised)
        self.frmExtent.setObjectName(_fromUtf8("frmExtent"))
        self.txtExtentSouth = QtGui.QLineEdit(self.frmExtent)
        self.txtExtentSouth.setGeometry(QtCore.QRect(140, 150, 221, 20))
        self.txtExtentSouth.setObjectName(_fromUtf8("txtExtentSouth"))
        self.txtExtentWest = QtGui.QLineEdit(self.frmExtent)
        self.txtExtentWest.setGeometry(QtCore.QRect(20, 100, 221, 20))
        self.txtExtentWest.setObjectName(_fromUtf8("txtExtentWest"))
        self.txtExtentNorth = QtGui.QLineEdit(self.frmExtent)
        self.txtExtentNorth.setGeometry(QtCore.QRect(140, 50, 221, 20))
        self.txtExtentNorth.setObjectName(_fromUtf8("txtExtentNorth"))
        self.txtExtentEast = QtGui.QLineEdit(self.frmExtent)
        self.txtExtentEast.setGeometry(QtCore.QRect(260, 100, 211, 20))
        self.txtExtentEast.setObjectName(_fromUtf8("txtExtentEast"))
        self.chkExtent = QtGui.QCheckBox(self.frmExtent)
        self.chkExtent.setGeometry(QtCore.QRect(10, 10, 461, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.chkExtent.setFont(font)
        self.chkExtent.setText(QtGui.QApplication.translate("WfsClient", "Use current Extent as Bounding Box Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.chkExtent.setObjectName(_fromUtf8("chkExtent"))
        self.txtFeatureTypeTitle = QtGui.QPlainTextEdit(self.frmMain)
        self.txtFeatureTypeTitle.setGeometry(QtCore.QRect(10, 100, 481, 31))
        self.txtFeatureTypeTitle.setReadOnly(True)
        self.txtFeatureTypeTitle.setObjectName(_fromUtf8("txtFeatureTypeTitle"))
        self.cmdMetadata = QtGui.QPushButton(self.frmMain)
        self.cmdMetadata.setEnabled(False)
        self.cmdMetadata.setGeometry(QtCore.QRect(360, 70, 131, 23))
        self.cmdMetadata.setText(QtGui.QApplication.translate("WfsClient", "Metadata", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdMetadata.setObjectName(_fromUtf8("cmdMetadata"))
        self.txtSrs = QtGui.QLineEdit(self.frmMain)
        self.txtSrs.setGeometry(QtCore.QRect(100, 440, 131, 20))
        self.txtSrs.setText(_fromUtf8(""))
        self.txtSrs.setObjectName(_fromUtf8("txtSrs"))
        self.lblSrs = QtGui.QLabel(self.frmMain)
        self.lblSrs.setGeometry(QtCore.QRect(10, 440, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lblSrs.setFont(font)
        self.lblSrs.setText(QtGui.QApplication.translate("WfsClient", "SRS", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSrs.setObjectName(_fromUtf8("lblSrs"))
        self.txtUsername = QtGui.QLineEdit(WfsClient)
        self.txtUsername.setGeometry(QtCore.QRect(120, 90, 381, 20))
        self.txtUsername.setObjectName(_fromUtf8("txtUsername"))
        self.txtPassword = QtGui.QLineEdit(WfsClient)
        self.txtPassword.setGeometry(QtCore.QRect(120, 120, 381, 20))
        self.txtPassword.setEchoMode(QtGui.QLineEdit.Password)
        self.txtPassword.setObjectName(_fromUtf8("txtPassword"))
        self.lblUsername = QtGui.QLabel(WfsClient)
        self.lblUsername.setGeometry(QtCore.QRect(20, 90, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lblUsername.setFont(font)
        self.lblUsername.setText(QtGui.QApplication.translate("WfsClient", "Username", None, QtGui.QApplication.UnicodeUTF8))
        self.lblUsername.setObjectName(_fromUtf8("lblUsername"))
        self.lblPassword = QtGui.QLabel(WfsClient)
        self.lblPassword.setGeometry(QtCore.QRect(20, 120, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lblPassword.setFont(font)
        self.lblPassword.setText(QtGui.QApplication.translate("WfsClient", "Password", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPassword.setObjectName(_fromUtf8("lblPassword"))
        self.cmdSaveUrl = QtGui.QPushButton(WfsClient)
        self.cmdSaveUrl.setGeometry(QtCore.QRect(350, 60, 151, 23))
        self.cmdSaveUrl.setText(QtGui.QApplication.translate("WfsClient", "Save URL as default", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdSaveUrl.setObjectName(_fromUtf8("cmdSaveUrl"))

        self.retranslateUi(WfsClient)
        QtCore.QMetaObject.connectSlotsByName(WfsClient)

    def retranslateUi(self, WfsClient):
        pass

